repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v6.0.0
    hooks:
    - id: check-json
      name: Check JSON files

    - id: check-yaml
      name: Check YAML files

    - id: end-of-file-fixer
      name: Check trailing newlines

  - repo: https://github.com/rvben/rumdl-pre-commit.git
    rev: v0.2.64
    hooks:
    - id: rumdl
      name: Check Markdown files
      args: ["--config", ".github/workflows/helpers/pre-commit/.rumdl.toml", "--fix"]

  - repo: local
    hooks:
    - id: wikilint
      name: Check MediaWiki files
      entry: wikilint
      args: ["--lint-config", ".github/workflows/helpers/pre-commit/.wikilint.json", "--strict", "--fix"]
      language: node
      additional_dependencies: ['wikilint']
      files: \.mediawiki$

  - repo: https://github.com/codespell-project/codespell.git
    rev: v2.4.3
    hooks:
    - id: codespell
      name: Check spelling (codespell)
      args: ["--ignore-words-list", ""]

  - repo: https://github.com/crate-ci/typos.git
    rev: v1.50.0
    hooks:
    - id: typos
      name: Check spelling (typos)
      args: ["--config", ".github/workflows/helpers/pre-commit/.typos.toml"]
