name: CI - Wiki

on:
  pull_request:
    paths:
      - 'wiki/**'
  push:
    paths:
      - 'wiki/**'

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: ${{ github.head_ref != '' }}

jobs:
  ci:
    name: Check
    runs-on: ubuntu-slim

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Setup nodejs
        uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'

      - name: Install tools
        run: |
          npm install
          npm ls
          echo "::group::npm ls --all"
          npm ls --all
          echo "::endgroup::"

      - name: Lint code
        run: npm run lint
